version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: /api
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo_data:

