version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - PORT=3000
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: ""
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo_data:
